Issue 153
ORNL-AMO/VERIFI pull request #253
Opened 2021-04-19 19:28 UTC by cranfillkd

Connects issue #153

2021-04-19 19:38 UTC, cranfillkd commented
This PR had several conflicts. I fixed them but let me know if they cause trouble during the review.

2021-04-19 20:26 UTC, rmroot requested changes

2021-04-19 20:26 UTC, rmroot commented on src/app/utility/help-panel/help-panel.component.ts
>    ngOnInit() {
I'm guessing this was a merge issue. We need the selected facility and save functions for the site to source section

2021-04-19 20:26 UTC, rmroot commented on src/app/utility/help-panel/help-panel.component.ts
> +    router.events.subscribe((route) => {
The help ends up blank right away if you don't navigate to the component. (on refresh)

in ngOnInit() the same logic can be used with this.router.snapshot.url (it doesn't update on events so will still need this). I'd create a function that takes the url and sets these two properties.

2021-04-19 20:26 UTC, rmroot commented on src/app/utility/help-panel/help-panel.component.html
> +        <ul>
Relative paths don't work in electron application but we don't use these .csv templates anymore. There's just the one xlsx template now

2021-04-20 13:43 UTC, rmroot approved these changes

2021-04-20 13:43 UTC, merged