separated styles.css into separate files, created toast.css to fix du…
ORNL-AMO/VERIFI pull request #314
Opened 2021-06-08 16:48 UTC by shivasaurus

connect #164

2021-06-09 18:43 UTC, rmroot requested changes
We should place all of these files in a styles folder instead of just src

2021-06-09 20:03 UTC, shivasaurus commented
CSS files have been placed into a styles directory

2021-06-10 17:52 UTC, cranfillkd approved these changes

2021-06-14 16:47 UTC, rmroot requested changes

2021-06-14 16:47 UTC, rmroot commented on src/app/electron/electron-update/electron-update.component.ts
> +  styleUrls: ['../../../styles/toast.css'],
In here and the toast component we *do not* want to update the styleUrls. The toast.css file should be a global style sheet like the others. I think it still needs to be loaded in angular.json

2021-06-14 16:47 UTC, rmroot commented on angular.json
> +              "src/styles/slidertoggle.css",
let's use camel casing to name these files. "sliderToggle.css" "profilePicture.css" etc..

2021-06-14 16:47 UTC, rmroot commented on src/app/electron/electron-update/electron-update.component.ts
> +  styleUrls: ['../../../styles/toast.css'],
If that doesn't work, let me know and I can dig in a bit to what's going on

2021-06-15 14:51 UTC, rmroot approved these changes

2021-06-15 14:52 UTC, merged