#32
ORNL-AMO/VERIFI pull request #315
Opened 2021-06-09 20:27 UTC by c-merchant

Added limits to input fields.

2021-06-10 18:13 UTC, cranfillkd commented on src/app/account-management/general-information-form/general-information-form.component.html
> +            <input type="text" class="form-control" formControlName="size" (input)="saveChanges()" onfocus="this.select();" minlength="1" maxlength="999999999999999">
I think you could probably limit this to around 60. At the point its 999999999999999, you wouldn't need to put a max on it.

2021-06-10 18:17 UTC, cranfillkd commented on src/app/account-management/sustainability-questions-form/sustainability-questions-form.component.html
> +                    (input)="saveChanges();" min="0" max="999999999999999">
Same as above

2021-06-10 18:24 UTC, cranfillkd commented on src/app/utility/energy-consumption/utility-meter-data/edit-electricity-bill/edit-electricity-bill.component.html
> +            [class.warning]="meterDataForm.controls.totalEnergyUse.value === 0" onfocus="this.select();" min="0" max="999999999999999999">
You can remove the max from these. Same for the ones below

2021-06-10 18:25 UTC, cranfillkd commented on src/app/utility/energy-consumption/utility-meter-data/edit-utility-bill/edit-utility-bill.component.html
> +          min="0" max ="999999999999999">
You can remove the max from these. Same for the ones below

2021-06-10 18:26 UTC, cranfillkd requested changes
Great work Charlotte. The main thing is to just remove or adjust the ones with 9e100.

2021-06-10 18:50 UTC, c-merchant commented
Got it. Thank you!

2021-06-14 15:51 UTC, cranfillkd approved these changes

2021-06-14 15:53 UTC, merged